Step3 - 문자열 계산기
next-step/android-calculator-mvp pull request #141
Opened 2023-02-02 15:51 UTC by jpoh281

안녕하세요? 세번째 PR 드립니다.

이번 과제를 하면서 느꼈던 고민들입니다. 

1. 공백을 입력하는 경우를 체크하는 테스트들이  모든 클래스의 테스트에 중복되게 들어갈 수 있는 것처럼 느껴져서 다 넣어야하는지, `Operator` 클래스에만 넣으면 되는지 고민이 되었습니다.

2. `value class`를 사용해보고 싶어서 사용했는데 이럴 때 써도 되는게 맞을까요?

3.  OperationTerm 이라는 인터페이스를 만들어 다형성을 통해 한 배열에 담을 수 있게 만들었는데 그것때문에 Calculate 클래스에서 다운캐스팅을 해야되게 만들어져버렸습니다. 더 좋은 방법이 있을까요?

항상 좋은 피드백 감사합니다! 🙇‍♂️

2023-02-04 06:17 UTC, dlwls5201 requested changes
변수명 하나하나까지 충분히 고민하시고 작업해주신 것 같아 로직에 관해서는 추가로 피드백을 드릴게 없네요 👍 로직 보다는 질문 주신 부분에 대해서 저도 함께 고민해보고 사소한 팁 몇가지 코멘트 남겼습니다.

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/test/java/com/example/domain/CalculatorTest.kt
> +        val calculator = Calculator()
`val calculator = Calculator()` 의 경우에는 멤버변수로 선언하여 사용해도 좋아 보입니다.
지금은 아니지만 만일 초기화를 매 테스트 마다 해야 된다면 @Before 을 활용해도 좋아보입니다 :)

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/test/java/com/example/domain/OperatorTest.kt
> +        }
**Junit4**에서 이렇게 테스트가 가능한지는 저도 처음 알았네요! 
**Junit5**의 `@ParameterizedTest`와 동일한 기능을 하네요. 저도 한 수 배워갑니다 👍

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/OperationParser.kt
> +    private fun toOperationTerm(term: String, index: Int): OperationTerm {
제가 생각하기에 홀수, 짝수 인덱스에 반환하는 값을 정하는 `toOperationTerm` 핵심 기능으로 보입니다.
이 부분도 테스트 코드에 추가해주세요.

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/OperationParser.kt
> +        return Operator.getByPrime(term)
굳이 return을 나눠 쓰지 않고 아래와 같이 해도됩니다.
```
return if (index % 2 == 0) {
            Operand.fromTerm(term)
        } else {
            Operator.getByPrime(term)
        }
```

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/Operand.kt
> +        }
`0`도 음수로 인식하기에 부등호 수정이 필요해보입니다.

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/OperationParser.kt
> +class OperationParser {
OperationParser 같은 경우에는 매번 객체를 생성할 필요 없이 싱글톤으로 만들어도 좋아보입니다.

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/Operator.kt
> +            val operator = values().find { operator ->
변수명에 예약어를 사용하고 있습니다. (operator)
가급적이면 예약어 사용을 지양하는 것이 좋습니다.

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/Calculate.kt
> +        return accumulator
> OperationTerm 이라는 인터페이스를 만들어 다형성을 통해 한 배열에 담을 수 있게 만들었는데 그것때문에 Calculate 클래스에서 다운캐스팅을 해야되게 만들어져버렸습니다. 더 좋은 방법이 있을까요?

[이 부분은 굳이 수정해 주시지 않아도 됩니다.]

저는 지금 방법도 충분히 좋다고 생각합니다. 다만 다운 캐스팅을 없애기 위해서는 다음과 같이 2가지 방법이 생각납니다.

1. terms 의 for 문을 돌며 타입이 `temp is Operator` 인지 `temp is Operand` 인지 확인하며 타입에 맞춰 로직을 수행합니다. 다만 여기서는 `index + 1` 이라는 다음 값을 미리 가져오는 로직이 있어 힘들어보이네요.

2. operationParser 에서 캐스팅까지 해서 반환해줍니다.
List<Pair<Operator, Operand>> 로 반환하여 전달할 수 있을 듯 합니다.
```
var accumulator = // 별도 초기화
terms.forEach { term ->
    val (operator, operand) = term
    accumulator = operator.execute(accumulator, operand.value)
}
```

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/test/java/com/example/domain/OperationParserTest.kt
> +}
https://kotlinlang.org/docs/coding-conventions.html#functions
함수가 복잡하지 않은 경우 `return` 대신 `=` 을 바로 사용하셔도 됩니다.

```
fun foo(): Int {     // bad
    return 1
}

fun foo() = 1        // good
```

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/main/java/com/example/domain/Operand.kt
> +value class Operand(val value: Int) : OperationTerm {
> value class를 사용해보고 싶어서 사용했는데 이럴 때 써도 되는게 맞을까요?

`value class`는 저도 처음봐서 간단히 레퍼런스를 보니 잘 사용하신 것 같습니다. 이부분은 저도 좀더 알아보고 추가로 코멘트 드리겠습니다 :)

2023-02-04 06:17 UTC, dlwls5201 commented on domain/src/test/java/com/example/domain/OperationParserTest.kt
> +    }
> 공백을 입력하는 경우를 체크하는 테스트들이 모든 클래스의 테스트에 중복되게 들어갈 수 있는 것처럼 느껴져서 다 넣어야하는지, Operator 클래스에만 넣으면 되는지 고민이 되었습니다.

테스트 코드의 의미가 로직을 테스트하는 것도 있지만, 문서화의 의미도 가지고 있습니다.
다른 개발자분들이 테스트 코드를 보았을 때, 함수의 구현부를 분석하지 않아도 기능을 이해할 수 있습니다. 
이런 관점에서 한번 고민해보면 되지 않을까 싶네요 🙂

2023-02-05 10:24 UTC, jpoh281 commented
안녕하세요? 리뷰 말씀해주신 부분에 따라 리뷰 수정했습니다.

> > 공백을 입력하는 경우를 체크하는 테스트들이 모든 클래스의 테스트에 중복되게 들어갈 수 있는 것처럼 느껴져서 다 넣어야하는지, Operator 클래스에만 넣으면 되는지 고민이 되었습니다.
> 
> 테스트 코드의 의미가 로직을 테스트하는 것도 있지만, 문서화의 의미도 가지고 있습니다. 다른 개발자분들이 테스트 코드를 보았을 때, 함수의 구현부를 분석하지 않아도 기능을 이해할 수 있습니다. 이런 관점에서 한번 고민해보면 되지 않을까 싶네요 🙂

해당 부분의 말씀을 듣고 생각해보면 결과 중복되더라도 있는게 더 나을 것 같다고 생각이 되었습니다.
또한 추후에 계산기에서 다른 방식으로 에러를 변환해서 던지게 할 때도 미리 테스트를 만들어 놓는게 훨씬 더 수월하게 할 수 있을 것 같아요.

> > OperationTerm 이라는 인터페이스를 만들어 다형성을 통해 한 배열에 담을 수 있게 만들었는데 그것때문에 Calculate 클래스에서 다운캐스팅을 해야되게 만들어져버렸습니다. 더 좋은 방법이 있을까요?
> 
> [이 부분은 굳이 수정해 주시지 않아도 됩니다.]
> 
> 저는 지금 방법도 충분히 좋다고 생각합니다. 다만 다운 캐스팅을 없애기 위해서는 다음과 같이 2가지 방법이 생각납니다.
> 
> 1. terms 의 for 문을 돌며 타입이 `temp is Operator` 인지 `temp is Operand` 인지 확인하며 타입에 맞춰 로직을 수행합니다. 다만 여기서는 `index + 1` 이라는 다음 값을 미리 가져오는 로직이 있어 힘들어보이네요.
> 2. operationParser 에서 캐스팅까지 해서 반환해줍니다.
>    List<Pair<Operator, Operand>> 로 반환하여 전달할 수 있을 듯 합니다.
> 
> ```
> var accumulator = // 별도 초기화
> terms.forEach { term ->
>     val (operator, operand) = term
>     accumulator = operator.execute(accumulator, operand.value)
> }
> ```
지금 방법이 괜찮다고 말씀해주셔서 수정을 하지는 않았습니다.
그래도 2안으로 적어주신 아이디어는 되게 좋은거같아요!! 감사합니다.

2023-02-05 11:28 UTC, dlwls5201 approved these changes
수정사항들을 커밋 별로 작업해 주셔서 쉽게 확인할 수 있었습니다. 👍 
다음 미션 진행해주세요!

2023-02-05 11:29 UTC, merged