Step1 모듈분리
next-step/android-calculator-mvp pull request #16
Opened 2022-01-26 14:30 UTC by ganghee

fork하고 기존 코드를  MVC에서 했던 과제로 대체 했습니다.

2022-01-26 14:52 UTC, laco-dev requested changes
안녕하세요!~
2주차 미션 동안 화이팅입니다.

domain 모듈의 패키지 수정이 필요할 것 같아 확인 부탁드립니다. 🙇

2022-01-26 14:52 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/Calculator.kt
> +package edu.nextstep.camp.calculator
domain 패키지로 분리가 되야하는데 누락된 것 같아요!~

2022-01-26 15:42 UTC, ganghee commented on domain/src/main/java/edu/nextstep/camp/calculator/Calculator.kt
> +package edu.nextstep.camp.calculator
네 수정하였습니다.

[refact: package명 수정](https://github.com/next-step/android-calculator-mvp/pull/16/commits/e10976171e715766c5d40c91ed3f15c43d19c9dc)

2022-01-27 14:22 UTC, laco-dev approved these changes
패키지는 app 기준으로 뒤에 domain을 붙여주는게 맞습니다! :)

`edu.nextstep.camp.calculator`
`edu.nextstep.camp.calculator.domain`

다음 단계에서 같이 변경 해 주세요~
빠른 진행을 위해 머지 하도록 하겠습니다.

2022-01-27 14:22 UTC, merged