4단계 - UI 테스트
next-step/android-calculator-mvp pull request #163
Opened 2023-02-10 10:27 UTC by hj1115hj

매번 질문 바로바로 답변해주시고 리뷰 꼼꼼히 해주셔서 감사합니다 ~ 덕분에 코드가 점점 깔끔해지고 있어용~

2023-02-10 12:39 UTC, BeokBeok requested changes
이전 단계 피드백과 UI 테스트 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
추가로, 일부 테스트 코드가 통과하지 못하고 있는데 확인 부탁드립니다. 🙏

2023-02-10 12:39 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +    }
프로그래밍 요구사항 중에 아래와 같은 항목이 있습니다.
```
- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
  - 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
  - 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.
```
이 요구사항을 반영해보면 어떨까요?

2023-02-10 12:39 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +    }
프로그래밍 요구사항 중에 아래와 같은 항목이 있습니다.
```
- indent(인덴트, 들여쓰기) depth를 2를 넘지 않도록 구현한다. 1까지만 허용한다.
  - 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
  - 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메서드)를 분리하면 된다.
```
이 요구사항을 반영해보면 어떨까요?

2023-02-10 12:39 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +                val newExp = exp.substring(0, exp.length - 1)
여기서 숫자 1은 어떤 것을 의미할까요?
숫자1과 같은 것을 "매직리터럴"이라고 합니다.
"매직리터럴"에 대해서 학습해보시고, 어떻게 개선해보면 좋을지 고민해보면 어떨까요?

2023-02-10 12:39 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +    }
코틀린에는 `Number` 라는 타입이 존재합니다.
함수명만 봤을 때에는 `Number`라는 타입을 판단해주는 것으로 보이지만, 구현체를 보니 Int 타입 변환 여부를 판단해주는 것 같네요.
구현체가 하고자 하는 일을 함수명에 좀 더 명확하게 드러내보면 어떨까요?

2023-02-13 11:52 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +    }
넵~ 그렇게 한다면 isInt가 좋을것 같아요 수정했습니다!

2023-02-13 12:11 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +                val newExp = exp.substring(0, exp.length - 1)
매직리터럴은 변하지 않는 상수값이거군요! 그래서 상수에 의미를 부여할 수 있구용! 1은 최소 연산할수 있는 숫자 단위이기 때문에 MINIMUM_NUMBER 로 변경하였습니다.

2023-02-13 12:30 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +    }
함수로 어떻게 만들어야할지 잘 생각이 안나서 공통 코트를 묵꼬 if문에 걸리면 return 하도록 해서 depth를 낮추었습니다.

2023-02-13 13:13 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-02-13 13:13 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +    }
Expression 클래스는 수식과 관련된 책임을 가지고 있습니다.
하지만, 계산과 관련된 책임도 가지고 있네요.
하나의 클래스에는 한 가지 책임만 갖도록(SRP) 코드를 개선해보면 어떨까요?

2023-02-13 13:13 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +                ((last.toInt() * 10) + input.toInt()).toString()
숫자10은 어떤 것을 의미할까요?
숫자 10이 어떤 것인지 상수로 정의해보면 어떨까요?

2023-02-13 13:13 UTC, BeokBeok commented on domain/src/main/java/camp/nextstep/edu/calculator/Expression.kt
> +        const val MINIMUM_NUMBER = 1
```suggestion
        private const val MINIMUM_NUMBER = 1
```
클래스 내부에서만 접근하는 변수라면, private 접근자를 붙여보면 어떨까요?

2023-02-13 13:13 UTC, merged