feat: 5단계 리팩터링
next-step/android-calculator-mvp pull request #170
Opened 2023-02-13 15:18 UTC by hj1115hj

feat: 5단계 리팩터링

2023-02-14 14:29 UTC, BeokBeok requested changes
이전 단계 피드백과 리팩터링 미션하시느라 고생하셨습니다. 👍 
잘 구현해주셔서 드릴 코맨트가 적네요. 😅 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-02-14 14:29 UTC, BeokBeok commented on app/src/main/java/camp/nextstep/edu/calculator/CalculatorContract.kt
> +        var presenter: Presenter
```suggestion
        val presenter: Presenter
```
인터페이스에서는 val로 정의해도, var로 오버라이딩이 가능해요.
이렇게 하게되면, 값의 변경이 필요한 곳에서는 var로, 값의 변경이 필요 없는 경우에는 val로 사용할 수 있어요.

2023-02-14 14:29 UTC, BeokBeok commented on app/src/main/java/camp/nextstep/edu/calculator/CalculatorPresenter.kt
> +        try {
try-catch문을 잘 활용해주셨네요. 👍 
지금도 잘 구현해주셨지만, runCatching을 활용해보면 어떨까요?

2023-02-14 14:29 UTC, BeokBeok commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +    fun `숫자가 입력되면 수식에 추가되고 변경된 수식을 보여줘야 한다`() {
given when then 형식으로 잘 구현해주셔서, 코드를 알아보기가 쉽네요. 👍

2023-02-28 14:59 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/calculator/CalculatorContract.kt
> +        var presenter: Presenter
그렇군요!
```kotlin
  override lateinit var presenter: CalculatorContract.Presenter 
```
이렇게 사용하는 쪽에서 오바라이딩 해서 사용할 수 있던 거네용~ 리뷰 감사드려요~

2023-02-28 15:08 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/calculator/CalculatorPresenter.kt
> +        try {
👍 👍  성공했을 경우 한 단계 분리해서 코드 작성할 수있으니 좋은 것 같아요!

2023-02-28 15:08 UTC, hj1115hj commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +    fun `숫자가 입력되면 수식에 추가되고 변경된 수식을 보여줘야 한다`() {
👍

2023-03-01 05:22 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
혜진님과 미션하면서 저 또한 성장하게 된 것 같습니다. 😄 
좋은 개발자가 되기 위한 소중한 경험이 되었길 바랍니다. 💪

2023-03-01 05:22 UTC, merged