4단계: 리펙터링
next-step/android-calculator-mvp pull request #176
Opened 2023-02-26 08:46 UTC by paksuua

주중에 시간을 많이 낼수 없었어서 지금에야 과제 제출하는점 죄송합니다🥲
제안해주신 Parameterized test로 반복되는 테스트 코드를 많이 줄일 수 있을 것 같아요! 다만 익숙치 않아서 이번 과제에는 적용하지 못했습니다 이후에 잘 소화해서 꼭 써보도록 할게요 감사합니다 ☺️📚
마지막 PR 올립니다~!

2023-02-26 15:06 UTC, malibinYun requested changes
이전 단계들의 피드백을 먼저 반영해주세요!
Parameterized Test에 대해서는 반영하지 않으셔도 좋지만, 다른 도메인에 대한 피드백에 대해서는 꼭 반영해주시면 좋겠어요 😀
변경사항이 많지 않아 크게 피드백 드릴 부분이 없었네요.
피드백들을 모두 반영하시고 다시 리뷰 요청 부탁드릴게요!

2023-02-26 15:06 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/calculator/CalculatorActivity.kt
> +        binding.buttonDivide.setOnClickListener { presenter.addInput(DIVIDE.operator) }
presenter에 바로 정수와 Operator를 넘겨보는 것은 어떨까요?

2023-02-26 15:06 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        assertEquals("1", actual)
Truth를 활용해주세요 :)

2023-02-26 15:06 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        verify { view.showExpression(actual) }
assert 구문을 나열하는 것과 assertAll로 감싸는 것은 어떤 차이가 있을까요?

2023-02-28 11:46 UTC, paksuua commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        verify { view.showExpression(actual) }
찾아보니 assert 구문이 여러개 있을 때 첫번째 assert 구문에서 테스트 케이스가 실패하면 이후 assert 구문은 실행되지 않네요 😮
이와 비교했을때 assertAll의 경우 assertion을 그룹화하여 그룹 내 모든 assert 구문을 실행하고 실패한 케이스들에 대해 각각의 기댓값, 결과값을 반환하는 것 같고..
정리하면 순차적으로 테스트를 실행하는지 병렬적으로 실행하는지 차이 맞을까요?👀

2023-03-01 09:51 UTC, paksuua commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        verify { view.showExpression(actual) }
Junit5부터 적용하는 기능인 것 같은데 써보고싶어서 PresenterTest에 넣어봤습니다 🌝

2023-03-01 09:52 UTC, paksuua commented
이전 과제 코멘트들 다시 확인해보고 빠진 부분 보충해서 다시 PR드립니다 🙇‍♀️

2023-03-02 05:22 UTC, malibinYun approved these changes
MVP미션 고생 많으셨어요! 👍
다른 피드백들도 꼭 반영해보시면서 공부해보셨으면 좋겠네요!
이번 미션은 이만 마무리 하도록 할게요 😀
고생 많으셨습니다 :)

2023-03-02 05:22 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/calculator/CalculatorPresenter.kt
> +        view.showExpression(result)
올바른 수식이 아니었을 때 에러 핸들링 하는 코드를 추가해보면 좋겠네요 :)

2023-03-02 05:22 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        verify { view.showExpression(actual) }
slot 없이, verify 할 때 메서드에 특정 파라미터를 넘겼는 지 검증해볼 수 있어요 :)

2023-03-02 05:22 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        every { view.showExpression(capture(inputSlot)) } answers { nothing }
아래 처럼도 작성할 수 있어요 :)
```suggestion
        every { view.showExpression(capture(inputSlot)) } just Runs
```

2023-03-02 05:22 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorPresenterTest.kt
> +        verify { view.showExpression(actual) }
asserAll은 Junit5의 기능인데, 제가 다른 강좌와 헷갈려서 잘못 소개해드렸네요 ㅠ_ㅠ
assertAll은 Junit4에서 지원하지 않으니, 사용하지 않으셔도 좋습니다.
지금 이것 때문에 CI가 Failed 되고있는 것 같네요!

사용하시게 된다면, verify 블럭도 검증문이니, assertAll 안에 넣어주셔야 합니다 :)

2023-03-02 05:27 UTC, merged