Step3 문자열 계산기 구현
next-step/android-calculator-mvp pull request #191
Opened 2023-07-27 15:46 UTC by suyong-park

- Domain 모듈에 계산 로직을 위한 Calculator, 입력값 검증을 위한 Validator 클래스 생성
- 문자열 계산식 계산 로직 추가

리뷰 잘 부탁드리겠습니다! 감사합니다.

2023-07-28 02:18 UTC, AnKyungMoo requested changes
고민해보면 좋을 점 코멘트로 남겨드렸어요!
수정 후 다시 요청주세요~!
질문사항 및 의논사항이 있다면 코멘트나 DM으로 연락주세요~!

2023-07-28 02:18 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/calculator/MainActivity.kt
> +    private val calculator by lazy { Calculator() }
Q: 어떠한 이유때문에 by lazy를 이용한 초기화를 진행하셨나요?
해당 케이스의 경우 Calculator를 바로 초기화해도 문제가 없어보여서 질문 드립니다!

2023-07-28 02:18 UTC, AnKyungMoo commented on domain/build.gradle.kts
> +    id("kotlin")
지난 리뷰의 요청 사항이 잘 반영되어있네요 👍 👍

2023-07-28 02:18 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/calculator/MainActivity.kt
> +    }
버튼의 클릭리스너를 다는 함수까지 통틀어서 함수로 만들기보단, 클릭리스너 안에 들어가는 내용이 함수로 정리되는 것이 더 의미상 정확한 구분으로 느껴지네요

이 부분 수정해보시는건 어떨까요?!

2023-07-28 02:18 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +class Calculator {
현재 Calculator가 너무 많은 책임을 가지고있네요~ (계산, 식의 변경, 연산 등등..)
책임을 조금 나눠보는 것은 어떨까요?

2023-07-28 02:18 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +    }
Q: 숫자와 연산식의 입력 방식이 나뉘어져야할 이유가 있나요?!

또한 입력받을 때마다 식을 검증하지 않으셔도 됩니다 ㅎㅎ; 보통은 계산 결과때 한 번에 검증합니다.

2023-07-28 02:18 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/Validator.kt
> +        if (expression.isEmpty() && number == 0) return
5 + 0 + 0 + 2 의 결과는 어떻게 나오나요!?

2023-07-28 02:18 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/domain/CalculatorTest.kt
0이나 음수에 관련한 테스트도 추가해보면 조금 더 정교한 테스트 코드를 만들 수 있습니다.

또한 validator에 대한 테스트도 만들면 만들었던 기능들을 조금 더 세분화해서 테스트 진행할 수 있습니다.

2023-07-28 04:04 UTC, suyong-park commented on app/src/main/java/camp/nextstep/edu/calculator/MainActivity.kt
> +    private val calculator by lazy { Calculator() }
A: 해당 객체를 사용하는 시점에 초기화를 시키게 되는 점 때문에 사용했습니다!
다만.. 최초 초기화시 값의 변동이 없다는 점에서 by lazy 를 굳이 사용할 이유가 없네요ㅎㅎ

2023-07-28 08:39 UTC, suyong-park commented on domain/src/main/java/camp/nextstep/edu/domain/Validator.kt
> +        if (expression.isEmpty() && number == 0) return
7이 노출됩니다!

2023-07-28 12:13 UTC, suyong-park commented on app/src/main/java/camp/nextstep/edu/calculator/MainActivity.kt
> +    }
어떻게 분리하는 것이 좋을까 많이 고민했던 부분인데, 아래쪽에 달아주신 "굳이 숫자와 연산식의 분리가 이루어져야 하는가" 와 함께 생각해보니 클릭리스너 안에 들어가는 내용이 함수로 분리되는 것이 맞을 것 같은 생각이 드네요ㅎㅎ
좋은 리뷰 감사드립니다 👍

2023-07-28 12:15 UTC, suyong-park commented on app/src/test/java/camp/nextstep/edu/domain/CalculatorTest.kt
0이나 음수에 대한 테스트를 추가하지 않았었네요.. 감사합니다ㅎㅎ
Calculator 에서 Validator 를 의존하므로 Calculator 만 테스트 하면 된다고 생각했었습니다.
테스트도 잘게 쪼개서 수행하는 것이 더 좋은 방법이겠네요. 감사합니다 👍

2023-07-28 12:29 UTC, suyong-park commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +class Calculator {
그렇네요... 다시 보니 너무 많은 책임을 들고 있군요.. 분리해 보겠습니다. 감사합니다 👍

2023-07-28 13:27 UTC, suyong-park commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +    }
해당 건은 입력된 문자가 사칙연산 기호가 아닌 경우 를 검증하기 위함으로 분리했었습니다.
계산 결과에서 한 번에 검증할 수 있도록 구현해 보겠습니다!

2023-07-30 10:22 UTC, AnKyungMoo requested changes
저번 리뷰 사항에 대해 열심히 고민해주신 것 같아서 너무 감사합니다 ㅎㅎ
하지만 다음 과제로 진행하기 전에 조금 더 확인하고 넘어가면 좋은 부분이 있어서 추가적으로 코멘트 남겼어요!

확인 후에 다시 리뷰 요청 주세요!

2023-07-30 10:22 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/domain/CalculatorTest.kt
> +    fun `사칙연산 기호가 아닌 경우 예외를 뱉는다`() {
어떤 예외가 throw되는지 명확하게 적어주는 것이 훨씬 더 정확한 테스트코드의 의미를 담을 수 있습니다.

2023-07-30 10:22 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/ExpressionHandler.kt
> +class ExpressionHandler {
식을 관리하는 객체를 새로 만든 것 너무 좋아요 👍 👍

2023-07-30 10:22 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/ExpressionHandler.kt
> +    fun getExpression() = expression
코틀린의 멤버변수는 프로퍼티의 특징을 가지고 있습니다.
따라서 getter 함수를 새로 만들기보다는 기본적으로 접근 가능하게 하는 것이 더욱 좋아요!

```suggestion
    var expression = ""
        private set
```

위와 같은 형태로 변경해보는 것은 어떨까요?!

2023-07-30 10:22 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/ExpressionParser.kt
> +    companion object {
특별한 상태를 가지지 않는 객체의 경우 특별히 객체로 두지 않아도 괜찮습니다.
```suggestion
object ExpressionParser {
```

2023-07-30 10:22 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +    private fun multiply(firstNumber: Long, secondNumber: Long) = firstNumber * secondNumber
계산기는 식을 계산한다는 책임만 가지고 있는 것이 더욱 좋을거같아요!
연산의 기능도 다른 객체에게 책임을 위임해보는 것은 어떨까요?

그리고 추가적으로 이 경우, 연산자가 새로 추가된다면 계속해서 분기가 늘어나가야합니다.
어떻게 진행하는 것이 좋을까요!?

2023-07-30 10:22 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/domain/ValidatorTest.kt
> +        }
숫자가 연속으로 입력되는 경우에는 124가 되어야해요!

2023-07-30 10:25 UTC, AnKyungMoo commented
> 테스트 코드를 올바르게 작성했는지 궁금합니다! ExpressionHandler, ExpressionParser 는 CalculatorTest 에서 테스트 하면서 함께 테스트 되기도 하고, 유의미한 테스트가 나오지 않을 것 같아 테스트 코드를 작성하지 않았는데 모든 public method 에 대한 단위 테스트를 작성하는 것이 맞는 것인지 궁금한 점이 있습니다.

함께 테스트 되긴하지만 각각의 객체별 상세 테스트가 존재하는 것이 훨씬 좋아요!
책임이 나눠지는 것과 같이 생각해보면 좋은데요~
ExpressionHandler에서 수정을 진행한 뒤, CalculatorTest에서 확인을 진행하게된다면 어느 부분에서 오류가 발생한 것인지 바로 파악이 되지 않아 추가 디버깅의 시간을 갖게 될 수 있을 것 같습니다.
각각의 객체의 함수들이 테스트된다면 빠르게 어느 부분에서 문제가 발생한 것인지 알 수 있는 장점이 있어요!

2023-07-30 11:30 UTC, suyong-park commented on app/src/test/java/camp/nextstep/edu/domain/CalculatorTest.kt
> +    fun `사칙연산 기호가 아닌 경우 예외를 뱉는다`() {
앗 그렇겠네요ㅎㅎ 감사합니다 반영하겠습니다!

2023-07-30 11:34 UTC, suyong-park commented on domain/src/main/java/camp/nextstep/edu/domain/ExpressionHandler.kt
> +    fun getExpression() = expression
앗..!! 그렇네요..!! 감사합니다ㅎㅎ

2023-07-30 11:36 UTC, suyong-park commented on app/src/test/java/camp/nextstep/edu/domain/ValidatorTest.kt
> +        }
이 부분은 제가 테스트코드를 잘못 작성한 것 같네요ㅎㅎ
의도는 사칙연산이 입력될 포지션에 숫자가 입력된 경우였어서 이 부분을 생각하다 보니 이렇게 되었군요ㅠ_ㅠ

2023-07-30 14:47 UTC, suyong-park commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +    private fun multiply(firstNumber: Long, secondNumber: Long) = firstNumber * secondNumber
최종적인 식만을 계산하는 것으로 책임을 부여한다면, Operator 객체를 새로 생성해 주는 것이 좋겠네요!

분기가 늘어나지 않고 연산자 추가 한번만으로 처리할 수 있는 방법을 고민해 보겠습니다ㅎㅎ

2023-07-30 16:25 UTC, suyong-park commented
남겨주신 코드 리뷰 사항을 반영했습니다ㅎㅎ

이번 커밋을 반영하면서.. (Calculator 에서 Operator 를 빼내고, 연산자가 추가되더라도 when 절에서 추가적인 작업을 하지 않아도 되게끔 하는 방법을 고민하는 데에 오래 걸렸네요)
기존의 Calculator 의 이름이 최종 연산식을 계산한다는 점에서 부적절하다고 생각해 Evaluator 로 변경하였습니다.
또, Operator 는 "연산자" 로써 단순히 연산자들만 열거한 것처럼 보일 수 있을 것 같다는 생각이 들어, CalculationOperator 로 명명하였습니다.

적절히 수정되었는지, 혹시 추가적으로 반영하면 좋을 부분이 있는지 알려주시면 감사하겠습니다!

좋은 리뷰 또 다시 부탁드리겠습니다ㅎㅎ 감사합니다!

2023-07-31 03:24 UTC, AnKyungMoo approved these changes
리뷰로 전달드린 부분이 적지 않았는데 잘 반영해주셨네요..!!
step3 고생 많으셨습니다!
추가적으로 반영할 부분 코멘트 남겨두었어요~

다음 과제 진행하시면서 같이 반영해주세요! 머지하도록 하겠습니다~

2023-07-31 03:24 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/domain/CalculationOperatorTest.kt
> +    fun `5 + 3 이 들어온 경우 IllegalArgumentException 이 발생하지 않고 8이 리턴된다`() {
"+ 기호의 경우, 합연산이 실행된다는 것"을 알려주는게 `CalculationOperatorTest`에서 전달해야될 항목으로 보입니다!
지금처럼 테스트함수명을 설정한다면 계산기에서 수행하는 것과 다르지가 않습니다

2023-07-31 03:24 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/calculator/MainActivity.kt
> +            buttonMultiply.setOnClickListener { showExpression(" × ") }
만들어두었던 enum을 사용하면 더욱 짜임새 있게 만들 수 있습니다!

2023-07-31 03:24 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/CalculationOperator.kt
> +        fun String.getCalculationResult(firstNumber: Long, secondNumber: Long): Long {
String의 확장함수가 아닌, 만들어진 enum을 사용할 수 있도록 변경해보면 좋겠습니다!

2023-07-31 03:24 UTC, merged

2023-07-31 03:25 UTC, AnKyungMoo commented
추가적으로 README에 개발 요구사항을 정리해보는 것은 어떤가요?!
테스트코드 작성시나, 기능 개발을 진행할 때 단위 나누는 것에 대해 도움을 줍니다!