Step3 - 문자열 계산기
next-step/android-calculator-mvp pull request #201
Opened 2023-07-30 15:32 UTC by kldaji

### 작업 내용
- 계산 담당 역할 Calculator 클래스 구현
- 사칙연산자 Operator enum 클래스 구현

### 참고사항
1. 예외 throw 테스트 코드가 이게 최선인지 잘 모르겠습니다 ㅎㅎ... 
2. 모든 모듈에 대한 테스트 코드를 test 모듈에 작성을 하는게 맞는지 의문이 들었습니다. test 모듈도 각 모듈별로 작성할 수 있는 방법이 있을까요??
3. 함수를 분리해본다고 나름 노력을 해보았는데, 함수를 너무 세분화해서 나누면 오히려 가독성이 안좋아질 것 같다는 생각이 번뜩 들기도 했는데요 ㅎㅎ.. 만약 리뷰어님이시라면 calculate 의 함수를 어떻게 세분화하셨을지 여쭤봐도 괜찮을까요??

2023-07-31 13:03 UTC, namjackson requested changes
안녕하세요! 
문자열 계산기 잘 구현해주셨네요! 
몇가지 참고하실만한 포인트들 코멘트 드렸으니, 확인해주세요! 
변경사항 적용후, 다시 리뷰요청해주시면 감사하겠습니다!

2023-07-31 13:03 UTC, namjackson commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +package camp.nextstep.edu.calculator
도메인 모듈의 테스트코드는 도메인 모듈에서 테스트 코드를 작성하면 어떨까요?

2023-07-31 13:03 UTC, namjackson commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +package camp.nextstep.edu.calculator
> 모든 모듈에 대한 테스트 코드를 test 모듈에 작성을 하는게 맞는지 의문이 들었습니다. test 모듈도 각 모듈별로 작성할 수 있는 방법이 있을까요??

각각의 모듈에 대한 테스트 코드는 각각의 모듈의 테스트 패키지에서 진행해주시면 좋을거같아요 😄 
https://developer.android.com/studio/test/test-in-android-studio?hl=ko#test_types_and_locations
공식문서를 가볍게 읽어보셔도 좋을거같아요 😄

2023-07-31 13:03 UTC, namjackson commented on domain/src/main/java/com/example/domain/Calculator.kt
> +package com.example.domain
`camp.nextstep.edu.calculator.domain` 와 같이 패키지를 규칙적 작성해보면 어떨까요?

2023-07-31 13:03 UTC, namjackson commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +			assertThat(e.message).isEqualTo(Calculator.EXP_NULL_OR_BLANK)
> 예외 throw 테스트 코드가 이게 최선인지 잘 모르겠습니다 ㅎㅎ...

assertThrows, ExpectedException 와 같은 키워드를 참고해보시면 좋을거같아요 😄

2023-07-31 13:03 UTC, namjackson commented on domain/src/main/java/com/example/domain/Calculator.kt
> +			}
Operator에 연산자가 추가될때마다, 함께 변경되어야하는 구조네요, 
연산자가 추가되더라도, Calculator에는 영향이 가지 않도록 변경해보면 어떨까요? 
Operator클래스 내에서 해당 로직을 가지고있다면 어떨까요?

2023-07-31 13:03 UTC, namjackson commented on domain/src/main/java/com/example/domain/Calculator.kt
> +		}
코틀린의 require, check 와 같은 키워드를 활용해보아도 좋을거같아요 😄

2023-07-31 13:03 UTC, namjackson commented on domain/src/main/java/com/example/domain/Operator.kt
> +enum class Operator(val op: String) {
enum class 활용 👍

2023-07-31 13:03 UTC, namjackson commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +	fun `공백 입력 테스트`() {
비슷한 테스트의 경우에는 Parameterized Test를 활용해도 좋을거 같아요 😄

2023-07-31 13:03 UTC, namjackson commented on domain/src/main/java/com/example/domain/Calculator.kt
> +	fun calculate(expression: String?): Int {
calculate 함수에서 많은 일을하는거 같아요! 
책임을 분리해보면 어덜까요?

2023-07-31 13:03 UTC, namjackson commented on domain/src/main/java/com/example/domain/Calculator.kt
> +	fun calculate(expression: String?): Int {
> 함수를 분리해본다고 나름 노력을 해보았는데, 함수를 너무 세분화해서 나누면 오히려 가독성이 안좋아질 것 같다는 생각이 번뜩 들기도 했는데요 ㅎㅎ.. 만약 리뷰어님이시라면 calculate 의 함수를 어떻게 세분화하셨을지 여쭤봐도 괜찮을까요??

객체 내부에 함수가 많아지거나, private 함수를 테스트하고 싶다면, 객체분리의 신호로 볼수도 있을거 같아요 😄 
책임을 기준으로 분리를 고민해보시면 좋을거같아요
표현식을 검증하고 파싱하는 역할의 객체를 추가로 나눠볼수 있을거 같아요

2023-07-31 23:22 UTC, kldaji commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +package camp.nextstep.edu.calculator
모듈별로 테스트 패키지를 생성할 수 있었군요!!

감사합니다!!

2023-07-31 23:53 UTC, kldaji commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +	fun `공백 입력 테스트`() {
junit5 는 안드로이드에서 공식적으로 지원하지 않는 것으로 기억하는데요!
단위 테스트에서는 junit5 를 사용해도 문제가 없는 것인지 궁금합니다!

2023-08-01 09:50 UTC, namjackson approved these changes
안녕하세요 !
피드백 반영 고생하셨습니다! 
몇가지 추가적인 코멘트 남겼으니, 확인해주세요! 
빠른 미션 진행을 위해 머지하겠습니다! 
변경사항은 다음미션에 포함해주세요 😄

2023-08-01 09:50 UTC, namjackson commented on domain/src/main/java/camp/nextstep/edu/domain/MyClass.kt
> +class MyClass {
불필요한 클래스는 제거해주세요 😄

2023-08-01 09:50 UTC, namjackson commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +		checkIsCompleteExpression(expression)
calculate에는 아직 여러 책임이 있는거 같아요! 
표현식에 대한 검증에 대한 책임을 분리 해보면 어떨까요?

2023-08-01 09:50 UTC, namjackson commented on domain/src/test/java/camp/nextstep/edu/domain/CalculatorTest.kt
> +	fun `null 입력 테스트`() {
케이스가 많아질수록, 테스트 케이스 명으로만 관리되기도하기 때문에
테스트 케이스는 좀더 구체적으로 작성해주시면 좋습니다!
`"계산식으 null일때, 계산하면, 에러가 발생한다"`와 같은 네이밍은 어떨까요? 
저는 개인적으로 케이스명도 규칙적으로 사용하곤합니다 
`<given>일때, <when>하면, <then>한다`

2023-08-01 09:50 UTC, namjackson commented on domain/src/test/java/camp/nextstep/edu/domain/CalculatorTest.kt
> +	fun `null 입력 테스트`() {
테스트 케이스를 구체적으로 작성한다면,
테스트 케이스를 하나의 요구사항 명세서처럼 활용하기도 합니다 👍

2023-08-01 09:50 UTC, namjackson commented on app/src/test/java/camp/nextstep/edu/calculator/CalculatorTest.kt
> +	fun `공백 입력 테스트`() {
여유가 되신다면, 미션과정을 통해서 한번 도입해보셔도 좋을거같아요 👍

2023-08-01 09:51 UTC, merged

2023-08-01 10:17 UTC, kldaji commented on domain/src/main/java/camp/nextstep/edu/domain/Calculator.kt
> +		checkIsCompleteExpression(expression)
아! 제가 의도를 잘못이해하고 calculate 내부에서 책임을 분리하려고 했었네요 ㅎㅎ;;
다음미션에 말씀주신대로 반영하도록 하겠습니다!