Step4 구현
next-step/android-calculator-mvp pull request #222
Opened 2023-08-22 15:34 UTC by suyong-park

안녕하세요!
회사 일이 많이 바빠지게 되어서 과제와 강의를 거의 수행하지 못했네요ㅠㅠ

늦더라도 틈틈히 시간날 때 계속 진행해 보려 합니다..!
Step4 를 수행하였습니다! 리뷰 부탁드리겠습니다 :)

2023-08-23 16:47 UTC, AnKyungMoo requested changes
전체적으로 코드를 잘 작성해주셨네요 👍 👍  
다음 step으로 넘어가기 전에 확인하고 넘어갔으면 좋겠는 부분이 있어서 코멘트 남겨두었습니다.
수정 후 다시 요청주세요!

추가적으로 README에 개발 요구사항을 정리해보는 것은 어떤가요?!
테스트코드 작성시나, 기능 개발을 진행할 때 단위 나누는 것에 대해 도움을 줍니다!

2023-08-23 16:47 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/Evaluator.kt
> +                    ?: CalculationOperator.PLUS
operator를 찾아주는 것을 함수로 변경해보는 것은 어떨까요?

2023-08-23 16:47 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/CalculationOperator.kt
> +        ): Long {
CalculationOperator.values().firstOrNull { it.symbol == expressions[i] }를 이용하여 operator를 찾아주고 있습니다.
그 뒤에, operator를 다시 인자로 받은다음 또 Enum에서 찾는 과정은 수행하지 않아도 됩니다.

어떻게 수정해보는 것이 좋을까요?

2023-08-23 16:47 UTC, AnKyungMoo commented on domain/src/main/java/camp/nextstep/edu/domain/ExpressionHandler.kt
> +            else deletedExpression
Nit: 연산자를 입력받으면서 띄어쓰기가 같이 포함되어있다보니 현재와 같은 식이 생겼네요..!
expression을 List<연산자 or 피연산자>가 들어올 수 있는 구조를 만든다면 훨씬 깔끔한 구문을 작성할 수 있습니다..!

해당 부분은 꼭 반영하진 않으셔도 괜찮습니다 :)

2023-08-26 08:59 UTC, suyong-park commented on domain/src/main/java/camp/nextstep/edu/domain/ExpressionHandler.kt
> +            else deletedExpression
이 부분은 고민을 했던 부분입니다ㅎㅎ 우선 해당 부분에 대해서는 고민해 보도록 하겠습니다!

2023-08-26 16:47 UTC, AnKyungMoo approved these changes
고생하셨습니다!!! 👍 👍 
DM으로 주셨던 내용은 추가 답변 드렸습니다!
다음 step으로 진행을 위해 머지하도록 하겠습니다 :)

2023-08-26 16:47 UTC, merged