Step3
next-step/android-calculator-mvp pull request #26
Opened 2022-01-29 13:45 UTC by ganghee

[refact: 에러처리에 대한 View의 로직을 Presenter에 위임한다.](https://github.com/next-step/android-calculator-mvp/commit/fbe9925928681b97ae050cd5f5f8645085cc8f66)
[test: Presenter 에러처리에 대한 테스트 코드 작성](https://github.com/next-step/android-calculator-mvp/commit/a62825bef5ac7cd04b1f84371f6790c8492e3d51)
위의 2개의 커밋은 지난 step2에서 요구사항을 적용한 커밋입니다.

4번째 커밋부터는 step3 요구사항을 적용하였습니다!!

 리뷰어님 설 연휴 잘 보내시고 설 연휴인데도 리뷰주셔서 감사드립니다. 🙇‍♂️

2022-02-01 07:09 UTC, laco-dev requested changes
3단계 미션 빠르게 진행 해 주셨네요 👍 

미션 요구사항에서 제시하는
> 계산 기록과 관련된 비즈니스 로직은 domain 모듈에 위치해야 한다.

에 따라서 관련 기능을 개선 해보면 좋을 것 같습니다
그 외에 추가적인 수정할만한 내용을 커멘트로 같이 남겼습니다.

2022-02-01 07:09 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/view/MainActivity.kt
> +                LinearLayoutManager(this@MainActivity, LinearLayoutManager.VERTICAL, false)
혹은 xml 에서 직접 선언할 수 있습니다.
```xml
app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
```

2022-02-01 07:09 UTC, laco-dev commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    }
여러가지 검증문을 호출하는 경우에는 assertAll { ... } 내에 같이 위치시켜주면 테스트 결과를 확인하는데 좋습니다.
```kotlin
assertAll(
    { verify { view.saveAddedStatement() } },
    { assertThat(statement).isEqualTo(presenter.statementList[0]) },
)
```

2022-02-01 11:27 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/model/Statement.kt
> +)
네 Record라는 이름을 붙여서 더 명시적으로 표현하는게 좋겠네요!

[refact: Record 이름을 붙여 명시적으로 수정](https://github.com/next-step/android-calculator-mvp/pull/26/commits/269707386124e20028bbdc9988008b381387180d)

2022-02-01 11:29 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/model/Result.kt
> +}
네 맞아요! 안그래도 자동 import될 때 계속 내장되어있는 Result객체로 되더라고요.
다음과 같이 수정했습니다

[refact: Result -> CalculateResult로 수정](https://github.com/next-step/android-calculator-mvp/pull/26/commits/1a645c593f0f92570b31f0f154fc6b1d194dd277)

2022-02-01 11:38 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/view/MainActivity.kt
> +    }
함수명을 바꾸고 파라미터로 받게 수정하였습니다

[refact: 저장된 수식 보여주기 기능 -> 함수명 수정, 파라미터 수정](https://github.com/next-step/android-calculator-mvp/pull/26/commits/83232168bb1fa87bc365134f6ce16f053ddc2c47)

2022-02-01 11:46 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/view/MainActivity.kt
> +    }
view에 showMemory(isVisible: Boolean)이라는 함수를 추가했습니다.
요청대로 계산 기록 화면이 떠 있는 상태에 키보드를 클릭하면 계산 기록 화면이 사라지게 구현했습니다.

toggle에 대해 궁금한 게 있습니다.
toggle에 대한 로직은 수정할 필요가 없어보이는데 의도한게 맞을까요?
``` kotlin
binding.recyclerView.isVisible = !binding.recyclerView.isVisible
```
이 로직 자체가 명확한 visibility를 받아 처리하도록 구현되어있다고 생각되어서요.
아니면 
``` kotlin
if(binding.recyclerView.isVisible){
     binding.recyclerView.visibility = INVISIBLE
}else{
     binding.recyclerView.visibility = GONE
}
```
이렇게 명시적인 로직을 의도한 건가요?

2022-02-01 11:52 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/view/MainActivity.kt
> +                LinearLayoutManager(this@MainActivity, LinearLayoutManager.VERTICAL, false)
xml에 layoutManager를 설정할 수 있다는 건 알고 있었는데 그렇게 하지 않은 이유는 로직을 분리 시킬려고 했습니다.
개인적인 코딩 스타일은 xml에는 뷰의 위치에 상테만 구현하는 게 맞다고 생각했어요. 
layoutmanager 같은 경우도 개념을 넓게 생각하면 뷰의 형식에 들어갈 수 있겠네요. 😄
LinearLayoutManager(context)로 줄여쓸수 있는 건 처음 알았네요!

[refact: recyclerView 생성자 수정](https://github.com/next-step/android-calculator-mvp/pull/26/commits/1487396dc75e33610efb49b5b8be7dd5075e48c5)

2022-02-01 11:53 UTC, ganghee commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    }
assertAll를 추가했습니다!

[test: assertAll 추가](https://github.com/next-step/android-calculator-mvp/pull/26/commits/6ecdf3ec5a5885f29941a16ec241b686d6e734f2)

2022-02-01 12:03 UTC, ganghee commented
[refact: model을 domain layer로 옮기기](https://github.com/next-step/android-calculator-mvp/pull/26/commits/75a50292d375a0cabde048ef7aa1608beea5d941)
[refact: 수식 저장 역할을 하는 객체 domain에 생성](https://github.com/next-step/android-calculator-mvp/pull/26/commits/0cd5e427e0d6d0fc6695156125ec9eb9dc85f51e)
[refact: 수식 저장 기능 Presenter에서 삭제하고 domain 객체에 위임하기](https://github.com/next-step/android-calculator-mvp/pull/26/commits/2751ff4ae92d9408a1aeaa3365147841162c144b)
[test: 수식 저장 테스트 수정](https://github.com/next-step/android-calculator-mvp/pull/26/commits/a2c8fa04ff02c42d4a4c15c185525cc38dd2042c)

위의 4개의 커밋은 수식 저장 기능을 presenter에서 domain으로 위임하는 내용을 담고 있습니다.
수식 저장 역할을 담당하는 CalculatorRepository 객체를 따로 생성했습니다.

2022-02-02 01:19 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/view/MainActivity.kt
> +                LinearLayoutManager(this@MainActivity, LinearLayoutManager.VERTICAL, false)
layoutManager도 RecyclerView의 attribute로 사용되기때문에 문제는 되지 않습니다.
비슷한 패턴으로는 AppbarLayout과 같이 사용하는 layout_behavior 같은게 있겠네요

2022-02-02 02:05 UTC, laco-dev requested changes
피드백 반영 확인했습니다.
2주차 미션의 마지막 단계인 만큼 추가적인 개선을 마무리하면 좋을 것 같아 몇가지 요청사항을 다시 커멘트로 남겼습니다 ㅎㅎ 🙇

2022-02-02 02:05 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorRepository.kt
> +    }
항상 가장 앞의 index에 데이터를 넣고 있는데 넣은 순서대로 데이터를 저장하고, 가장 마지막의 항목을 꺼내오는게 더 자연스러울 것 같습니다. 🤔

2022-02-02 03:26 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/view/MainActivity.kt
> +    }
아 네 그런 의도였군요!!
presenter에서 계산 기록 화면 상태를 가지고 있는 것도 좋은 방법이네요!

2022-02-02 04:48 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/presenter/MainPresenter.kt
> +        view.showSavedStatement(calculatorRepository.recordStatementList.first())
아 캡슐화하는 걸 잊었네요!
인터패이스를 만들어서 리스트를 외부에 노출시키지 않도록 구현했습니다.

[refact: recordStatementList 캡슐화](https://github.com/next-step/android-calculator-mvp/pull/26/commits/995473f2a2ee8ad808a71916d8b45e7de04efbf6)

2022-02-02 04:55 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/MainContract.kt
> +        fun showSavedStatement(recordStatement: RecordStatement)
showSavedStatement 같은 경우에는 recyclerView adapter와 관련되어 있어서 notify로 명명하는게 좋다는 거죠?
그러면 view는 recoardStatement는 수신 받고 보여주는 것은 정확히 말하면 adapter에 위임해서 맨 마지막에 보여줄지
처음에 보여줄지 판단하는 거고요. view에서 binding과 바로 연관되어 있다면 이름을 show로 해도 상관없고요.
제가 이해한게 맞을까요?

[refact: 명확한 변수명 notifyRecordStatement로 변경](https://github.com/next-step/android-calculator-mvp/pull/26/commits/2965ba37018dc274eb3e8503a390ec2662331b7f)

2022-02-02 04:56 UTC, ganghee commented on app/src/main/java/edu/nextstep/camp/calculator/MainContract.kt
> +        fun saveStatement(recordStatement: RecordStatement)
네! 멤버 메서드로 변경하였습니다.

[refact: saveStatement 멤버 메소드로 변경](https://github.com/next-step/android-calculator-mvp/pull/26/commits/194cf96db1aa5e0e168971a07c8568389b3f7afa)

2022-02-02 04:59 UTC, ganghee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorRepository.kt
> +    }
네네 보여주는 것이 리스트의 0부터 보여주고 있어서 데이터 저장할 때도 0에 저장하려고 했네요.
마지막에 저장하고 보여줄 때만 adapter에서 리스트 0부터 보여주는 게 좋을 것 같네요

[refact: list index 마지막에 저장으로 변경](https://github.com/next-step/android-calculator-mvp/pull/26/commits/b56496f077a6bd7decb8d2af12af3eb5ef9e005c)

2022-02-02 06:20 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/MainContract.kt
> +        fun showSavedStatement(recordStatement: RecordStatement)
네. View가 제공하는 인터페이스로 바라봤을때 `showXXX` 라는 형태의 패턴이면 무언가가 보일 것이라는 추측을 할 수 있는데 실제 동작은 아무것도 변하지 않아서 그렇습니다.

단순히 인터페이스 이름만으로 봤을 때
`showSavedStatement` --> 이건 파라미터로 넘긴 SavedStatement를 보여주는 것이구나?
`notifyRecordStatement` --> 이건 무언가 콜백을 받나보네? 어떤 동작을 하는지는 실제 구현체를 봐야 알겠구나?

Presenter 입장에서는 View가 어댑터에 위임할지 토스트로 보일지, 텍스트뷰에 보일지를 결정할 수 없기 때문에 Callback 형태의 이름으로 정해서 View에게 처리를 위임시키는 거로 볼 수 있습니다.
(다른 개발자가 봤을 때 오해를 남기지 않기 위함)

2022-02-02 06:34 UTC, laco-dev approved these changes
피드백 반영 확인했습니다.

처음 제출해주셧을때와 비교해서 많은 부분이 개선되서 좋았습니다. 👍 
MVP 미션에서는 Controller의 역할을 Presenter로 분리하는데 집중을 해 보았다면 이후 MVVM에서는 View의 상태를 ViewModel로 모델링하는 전략에 대해 같이 경험 해 보시면 될 것 같습니다.

간단한 의견 남겼는데 한번 읽어 보시면 됩니다. :)
2주차 미션 종료하겠습니다. 👍

2022-02-02 06:34 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorRepository.kt
> +    fun getRecordStatement(): RecordStatement = recordStatementList.last()
`getLatestRecordStatement()` 🤔  ???

2022-02-02 06:34 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/view/RecordAdapter.kt
> +    }
지금은 아이템 하나를 받아서 업데이트 하는 형태로 만들어 보았다면,
다음에 기회가 될 때에는
ListAdapter를 이용해 List를 그대로 넘겨주는 방법을 한 번 찾아 보도록 하세요~

https://developer.android.com/codelabs/kotlin-android-training-diffutil-databinding#0

2022-02-02 06:34 UTC, merged