Step2
next-step/android-calculator-mvp pull request #45
Opened 2022-02-06 06:47 UTC by jinjinchoi

2022-02-06 09:04 UTC, laco-dev requested changes
MVP 분리 정말 잘 해주셨네요. 👍 

로직은 특별히 문제될 점이 없어서 테스트 코드 관점에서 몇 가지 수정 요청 드립니다.

2022-02-06 09:04 UTC, laco-dev commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    fun `수식이 주어졌을 때, 화살표 기호가 입력되면 수식의 마지막 원소를 지워야 한다`() {
예상하는 기대값과 결과가 테스트에 들어날 수 있도록 보다 구체적으로 작성 해 주시면 좋겠습니다.
이 테스트의 경우
```kotlin
"11 + 3"이 주어졌을 때, 마지막 항목을 지우면 "11 + "가 보여야 한다.
```
로 나타낼 수 있을까요?

2022-02-06 09:04 UTC, laco-dev commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    fun `수식이 주어졌을 때, 화살표 기호가 입력되면 수식의 마지막 원소를 지워야 한다`() {
다른 테스트코드도 같습니다!~

2022-02-08 10:33 UTC, jinjinchoi commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +        Toast.makeText(this, R.string.incomplete_expression, Toast.LENGTH_SHORT).show()
미처 고려하지 못한 부분이네요ㅎㅎ 제공해주신 예시가 훨씬 직관적인 것 같습니다. 수정 반영하겠습니다!

2022-02-08 10:35 UTC, jinjinchoi commented on app/src/main/java/edu/nextstep/camp/calculator/MainContract.kt
> +}
하하 사실 홈페이지에 있는 예시 보고 참고한 것인데(..) 말씀해주셔서 왜 좋은지 제대로 깨달았네요ㅎㅎ 감사합니다

2022-02-08 10:42 UTC, jinjinchoi commented on app/src/main/java/edu/nextstep/camp/calculator/MainPresenter.kt
> +    private var expression = Expression.EMPTY
아아 요렇게 멤버 변수로 선언하지 말고 생성자로 calculator랑 expression을 넣어보라는 말씀이시죠? 해보겠습니다ㅎㅎ

2022-02-08 10:51 UTC, jinjinchoi commented on app/src/main/java/edu/nextstep/camp/calculator/MainPresenter.kt
> +    private var expression = Expression.EMPTY
수정 반영했습니다! 다만 제가 아직 구조적인 부분에 대해서 장단점을 논리적으로 말할 수 있는 수준이 아니라서요ㅎㅎ (이 구조로 하면 이러이러 해서 좋다 요런걸 똑부러지게 주장하지 못한다는 뜻) 혹시 이렇게 해줄 경우에 `테스트 코드에서 반복적인 Presenter 로직을 대체할 수 있`다는 것 외에 또 어떤 이점들이 있을지 말씀해주실 수 있을까요?ㅎㅎ

2022-02-08 11:06 UTC, jinjinchoi commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +        every { view.showExpression(capture(expressionSlot)) } answers { nothing }
윽 relaxed를 나중에 추가해줬었는데
그러고 나니 view.showExpression는 불필요하게 mocking했네요!
싹 제거했습니다

2022-02-08 11:08 UTC, jinjinchoi commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    fun `수식이 주어졌을 때, 화살표 기호가 입력되면 수식의 마지막 원소를 지워야 한다`() {
아하 backtick 사이에 기호를 넣을 수가 없어서요, 주석으로 추가하겠습니다! (혹시 다른 방법이 있다면 알려주셔도 감사하겠습니다)

2022-02-08 13:04 UTC, laco-dev commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    fun `수식이 주어졌을 때, 화살표 기호가 입력되면 수식의 마지막 원소를 지워야 한다`() {
Junit5 기반의 테스트 환경에서는 `@DisplayName()`으로 사용이 가능한데 Juni4 에서는 안됩니다. ㅠㅠ

2022-02-08 13:14 UTC, laco-dev approved these changes
피드백 반영 확인했습니다 👍 

3단계 미션에서 새로운 도메인 로직을 만들어 보면서 지금의 MVP 구조에 맞게 적용 해 보세요~

2022-02-08 13:14 UTC, merged