🚀 step 2
next-step/android-calculator-mvp pull request #67
Opened 2022-07-20 13:06 UTC by greedy0110

- MainContract 구성
- MainPresenter 구현

2022-07-21 04:28 UTC, devsoupe requested changes
'2단계 - 계산기 (MVP)' 미션 고생 많으셨습니다.
고민해볼만한 내용들을 피드백으로 남겨드렸으니 확인 부탁드리겠습니다.
반영 이후에 다시 리뷰 요청해주세요. 😉

2022-07-21 04:28 UTC, devsoupe commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/MainContract.kt
> +        fun delete()
delete를 addToExpression 처럼 조금더 의미있는 이름으로 바꿔보시는건 어떨까요? 🙂

2022-07-21 04:28 UTC, devsoupe commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/MainContract.kt
> +class MainPresenter(
MVP 구조에서 Contract와 Presenter는 도메인 모듈이 아닌 앱 모듈에 작성해주셔야 합니다.
MainContract, MainPresenter는 분리해주시고 MainActivity, MainContract, MainPresenter가 같은 package에 있도록 해주시면 됩니다. 
Presenter가 옮겨짐에 따라 PersenterTest로 함께 옮기시면 될 것 같습니다. 🙏

2022-07-21 16:00 UTC, devsoupe commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/MainContract.kt
> +class MainPresenter(
**1. 혹시, Presenter가 앱 모듈에 들어가야하는 이유가 뭔지 알 수 있을까요? 일반 자바 객체로 도메인 모듈에 포함해도 되지 않나 생각했었습니다. 🙏 MVVM, MVP 등의 구조에서 Model에 해당하는 부분만 domain으로 추출하는 걸 의도하는 걸까요?**

```
우선 domain 모듈과 MVP 구조는 분리해서 생각해주시면 좋을 것 같습니다. 초기 안드로이드 빌드시스템에서는 멀티 모듈 형태로 개발이 진행되지 않았고, 한개의 모듈안에서 어떻게 하면 뷰와 비지니스 로직을 분리해서 개발할지에 대한 논의들만 있었습니다. 웹 모델에 기반한 MVC 같은 아키텍쳐가 등장했으며 View파일, Controller파일, Model파일의 구조는 자신이 원하는 형태로 관리했습니다. 화면 기준으로 한 폴더에 view, controller, model 파일을 모아 개발하는 구조도 있었고, 화면과 상관없이 view, controller, model 파일 기반으로 폴더를 만들어 개발하는 구조도 있었습니다.

domain 이라는 멀티 모듈을 나누어 개발하기 시작한건 gradle 빌드시스템으로 넘어오고 난후 Clean Architecture가 모바일 개발에도 적용되기 시점부터였습니다. MVC, MVP, MVVM에서 View를 제외하고 나머지 부분의 핵심 비지니스로직과 데이터들이 domain, data 모듈로 적절히 나뉘게 되었습니다. 

클린 아키텍처 기준 남겨진 P, C, VM은 domain, data 모듈과의 가교 역할과 화면에 대한 로직(이벤트, 상태)들을 제어하는 역할로 남겨지게 되어 관례상 Activity(Fragment) 파일과 동일한 위치에 있게 된게 아닌가 하는 생각입니다.
```

**2. 그렇게 했을 때, app 모듈에 연관있는 코드에 대한 테스트는 안드로이드 의존성 등 때문에 테스트 빌드 - 실행 주기가 늘어질 수 있지 않을까요?**

`app 모듈에 있다고 해서 모든 테스트가 안드로이드에 의존적인것은 아닙니다. app 모듈에도 안드로이드에 의존적인 테스트는 androidTest에 일반 유닛 테스트는 test에 위치하게 됩니다. 구현하신 MainPresenterTest는 test에 위치시키시면 되고 안드로이드에 의존적이지 않으므로 이로인한 빌드 - 실행주기가 늘어나진 않습니다.`

2022-07-21 16:02 UTC, devsoupe commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/MainPresenterTest.kt
> +    }
어떤 질문인지 정확히 이해가 되질 않습니다. ㅠ
다시 한번 나누어서 질문을 설명해주시면 감사하겠습니다.

2022-07-22 15:09 UTC, devsoupe approved these changes
'2단계 - 계산기 (MVP)' 미션 고생 많으셨습니다.
간단하게 고민해볼만한 내용들을 피드백으로 남겨드렸으니 확인 부탁드리겠습니다.
다음 미션을 진행하시면서 필요하다고 생각되시는 피드백은 반영부탁드리겠습니다. 🙏

2022-07-22 15:09 UTC, devsoupe commented on app/src/main/java/edu/nextstep/camp/calculator/MainContract.kt
> +        fun calculate()
removeLastFromExpression
calculateExpression 이었으면 좀더 명확할 것 같습니다. 😅

지금처럼 간단한 코드에서는 removeLast, calculate이 크게 문제가 되거나 하는건 아니지만
사소한 API 명이라도 조금더 신경을 쓰신다면 더 나은 '협업'이 되지 않을까 하는 생각에 말씀드렸습니다.

수정하실 필요는 없고 참고만 해주세요!

2022-07-22 15:09 UTC, devsoupe commented on app/src/main/java/edu/nextstep/camp/calculator/MainContract.kt
> +interface MainContract {
View, Presenter 인터페이스를 적절하게 잘 나누어 주셨습니다.
Contract만 보아도 Presenter가 View에 어떤식으로 화면을 표현해주기를 요청하는지,
View는 Presenter에 어떤 기능을 수행하길 원하지를 잘 나타내고 있는것 같습니다. 👍

2022-07-22 15:10 UTC, merged

2022-07-23 01:55 UTC, greedy0110 commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    }
`given 절에 의해서 2번 실행되었고, calculate 이후에는 showExpression 실행이 없다`를 전달하고 싶었습니다. 혹시 이러한 의도를 전달하고 싶을 때 사용할만한 방법이 있을까요?

2022-07-23 03:06 UTC, devsoupe commented on app/src/test/java/edu/nextstep/camp/calculator/MainPresenterTest.kt
> +    }
검색해보니 이런식으로 표현이 가능하네요.

```suggestion
    fun `show fail message and do nothing with display when calculate on uncompleted expression`() {
        // given "1 *"
        presenter.addToExpression(1)
        presenter.addToExpression(Operator.Multiply)
        verify(exactly = 2) { view.showExpression(any()) }
        
        clearMocks(view) // or clearAllMocks()

        // when
        presenter.calculate()

        // then
        verify { view.showCalculationFailMessage() }
        verify(exactly = 0) { view.showExpression(any()) }
    }
```

만일 Mock 객체의 모든 함수가 호출되지 않았음을 표현할때는 좀더 간단하게 표현됩니다.
verify { view wasNot Called }

저도 called 되지 않았음을 활용해보진 않았는데 주신 질문으로 찾아보게되었네요. 감사합니다! 👍